### ISSUE TITLE
Produce specific error messages

### ISSUE THREAD

**Issue by axelrindle** [tarunbatra/password-validator#38]
Let's say my schema looks like this:

```js
const passwordSchema = new PasswordValidator()
  .is().min(8)
  .is().max(32)
  .has().letters()
  .has().digits();
```

Now when i validate a given password, the only thing I get in return is an array of rule names, like this:

```js
const errors = passwordSchema.validate('short', { list: true });
// => ['min', 'digits']
```

It would be better to return specific error message, like the following:

```js
const errors = passwordSchema.validate('short', { list: true });
// => ['Must have a minimum length of 8!', 'Must contain digits!']
```

Or, to make it less opinionated, just return the method name with the specified parameter, so I can create custom error messages:

```js
const errors = passwordSchema.validate('short', { list: true });
// => [ { method: 'min', arg: 8 }, { method: 'digits' } ]
//        Minimum length of 8        Must contain digits
```

**Comment by tarunbatra** [comment]
I thought about this while implementing `list` option and decided not to return context like `arg` in response because:
- It won't work for most of the validations, like `digits` and `letters`.
- The application code would already know the argument to `min` method. eg:
```js
const MIN_LENGTH = 8;
const passwordSchema = new PasswordValidator();
passwordSchema.is().min(MIN_LENGTH);
```
```js
const errors = passwordSchema.validate('short', {list: true});
let errorMsg = 'Error!';
if (errors.includes('min')) {
    errorMsg = `Must have a minimum length of ${MIN_LENGTH}!`
}
return errorMsg;
```
I understand that whether or not the argument is available in the context or not depends on the way application is structured. But this is the way I'd want to promote.

Let me know if you think this is not the way to go.

**Comment by axelrindle** [comment]
Why wouldn't this work for validations like `digits` and `letters`? The returned message could just be something like `must contain at least one digit!`.

I understand your point that the application code already knows the arguments. Though this might be true for small applications, but in my case the file where I define my validations is another than where I actually validate incoming requests.

Of course there are ways how I can resolve this with custom logic, but I think it would be a smarter approach to implement this logic directly into this package.

**Comment by tarunbatra** [comment]
> Why wouldn't this work for validations like digits and letters? The returned message could just be something like must contain at least one digit!.

For digits and letters, you can return an error message, but that's too opinionated IMO. I made that point in the context of returning arguments like you suggested here:
> // => [ { method: 'min', arg: 8 }, { method: 'digits' } ]
This approach wont work for validators like `digits` because there are no arguments provided.

Don't see how this thing can be achieved without being opinionated about error messaging. For now, would leave this on the application.

**Comment by contactsamie** [comment]
Sorry for chiming in after this is closed. Thanks for the library btw. Some times especially when building real quick app, clients may want it 'opinionated' as long as it's not forced , it will make dev fast to implement, and less code. returning 'digits' instead of 'number' is already an opinion, its just to what degree do we want to take the opinion. Does that make sense @tarunbatra  ?

**Comment by tarunbatra** [comment]
Thanks for the input @contactsamie. Now that most of the validations support an argument, this issue makes more sense to me. I'm still not sure how can this be done in a non-opinionated manner. Something off the top of my head would be like:
```js
const passwordSchema = new PasswordValidator();
passwordSchema.is().min(8);
passwordSchema.validate('short', { errorMessages: true });
// [ 'Must have a minimum length of 8' ]
```
Do give your opinion on the design of this feature if it was to exist. Meanwhile I'm also looking at [express-validator](https://express-validator.github.io/docs/custom-error-messages.html) for inspiration.

**Comment by kevinlandsberg** [comment]
Hey @tarunbatra ,

why dont you just add a parameter to validate function, which allows to return an object with criteria property and failed validations?

**Comment by tarunbatra** [comment]
Hi @kevinlandsberg, correct me if I'm wrong but how is it different from the `list` option provided by [`validate`](https://tarunbatra.com/password-validator/5.1.0/PasswordValidator.html#validate) method.

**Comment by kevinlandsberg** [comment]
Hi @tarunbatra ,

i meant something like this:

`validate('password123', { getAllInfos: true })`

returns:

```
{
   isValid: true,
   failedValidations: ['min', 'max', 'digits', 'spaces'],
   criteria: [
      {
         method: 'min',
         value: 8
      },
      {
         method: 'max',
         value: 100
      },
      {
         method: 'digits',
         value: 2
      },
      {
         method: 'spaces',
         value: 0
      }
   ]
}
```

With these informations you can add your own errormessages...

**Comment by tarunbatra** [comment]
This is a good suggestion, @kevinlandsberg . I would suppose the new parameters can be called `details`. If it is set, an object with all the rules applied, failed/passed can be returned. With this out possible in `v6`, maybe the `list` option can be deprecated.
